= Janus
Tomas Stenlund
PA1 2022-06-06
:description: An issue and requirements tracker for development and maintenance of products and services, focusing on the entire life cycle.
:page-layout: portrait

{description}

NOTE: From **wikipedia**: In ancient Roman religion and myth, Janus (/ˈdʒeɪnəs/ JAY-nəs; Latin: Ianus [ˈi̯aːnʊs]) is the god of beginnings, gates, transitions, time, duality, doorways, passages, frames, and endings.

It will contain support for teams, product owners and single individuals tasks to maintain the product or service.

== Status
The project is in the design and startup phase. It started 2022-06-06 and is currently working on a first sprint of the system design that will contain early sketches of the solution, information model and user interface to get started.

== Introduction
This section points mostly to other documents covering different areas for the product.

=== Ways of working

=== System Design

=== Toolchain

=== Frontend

=== Backend

=== Documentation
